name = "CurricularAnalytics"
uuid = "593ffa3d-269e-5d81-88bc-c3b6809c35a6"
authors = ["Greg Heileman <gregheileman@gmail.com>", "Hayden Free <hayden.free@uky.edu>", "Orhan Abar <orhan.abar@uky.edu>", "Will Thompson <wgthompson@uky.edu>"]
version = "0.6.2"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
Bukdu = "3e78a19a-cc83-51d8-955b-515f39fd7955"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MultiJuMP = "f6097e2c-3ba3-5605-a9a8-3a277acb490f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"

[compat]
Blink = "0.12.0"
Bukdu = "0.4.4"
CSV = "0.5.9"
DataFrames = "0.19.1"
DataStructures = "0.17.0"
Documenter = "0.23.0"
HTTP = "0.8.4"
JSON = "0.21.0"
JuMP = "~0.18.5"
LightGraphs = "1.2.0"
MathOptInterface = "0.9.0"
MultiJuMP = "0.5.0"
Plots = "0.25.3"
Requires = "0.5.2"
StatsPlots = "0.11.0"
WebIO = "0.8.8"
julia = "1.0, 1.1, 1.2"
